### ISSUE TITLE
Client did not get response within 3000 ms

### ISSUE THREAD

**Issue by mouthzipper** [recombee/js-api-client#2]
I seldom get this error when calling `client.send(new recombee.AddDetailView(userId, itemId))`. It's hard to replicate but this is based on our sentry logging. Any possible reason? or any configuration to increase timeout?

**Comment by OndraFiedler** [comment]
It is typically caused by network issues or slow internet connection (e.g. mobile connection) of the end users.
What is the portion of these cases to all sent detail views?

The timeout can be increased like this:
```js
var r = new recombee.AddDetailView(userId, itemId);
r.timeout = 10000; // 10 seconds
```
It can help in case of slow connection, but will not help if there is a large packet loss in the connection.

**Comment by mouthzipper** [comment]
@OndraFiedler  Thanks for the response.
I only need to know how to manually configure timeout.

As for the use case, we have an app that will send an event to recombee on every page visit of that specific item/page.

**Comment by pablotardio** [comment]
So thanks, i didn't know that timeout was a parameter
